name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64", "amd64_x86"]
        build-type: ["Debug", "Release", "RelWithDebInfo"]

    steps:
    - uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Configure
      run: cmake --preset default
    
    - name: Build
      run: cmake --build --preset default --config ${{matrix.build-type}}
    
    - uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.build-type}}-${{matrix.arch}}
        path: |
          ${{github.workspace}}/build/${{matrix.build-type}}/
